export const CHANGE_FORM_SCHEDULE = "CHANGE_FORM_SCHEDULE";
export const CLEAR_FORM_SCHEDULE = "CLEAR_FORM_SCHEDULE";
export const SCHEDULE_EDIT = "SCHEDULE_EDIT";
export const SCHEDULE_TODAY = "SCHEDULE_TODAY";
export const SCHEDULE_EXAM = "SCHEDULE_EXAM";