export const QUESTION_FORM = "QUESTION_FORM";
export const QUESTION_CLEAR_FORM = "QUESTION_CLEAR_FORM";
export const QUESTION_GET_ROW = "QUESTION_GET_ROW";
export const QUESTION_TO_STUDENT = "QUESTION_TO_STUDENT";
export const QUSTION_LIST = "QUSTION_LIST";
export const QUESTION_NAV = "QUESTION_NAV";
