export const FORM_USER = "FORM_USER";
export const MESSAGE_AUTH = "MESSAGE_AUTH";
export const IS_SUCCESS_AUTH = "IS_SUCCESS_AUTH";
export const CLEAR_FORM_AUTH = "CLEAR_FORM_AUTH";
export const MESSAGE_ERROR_AUTH = "MESSAGE_ERROR_AUTH";
export const GET_USER_DATA = "GET_USER_DATA";
